import { DiseaseClass, DiseaseRecommendation } from '@/types';

export const DISEASE_RECOMMENDATIONS: Record<DiseaseClass, DiseaseRecommendation> = {
  Healthy: {
    pesticide: 'No spray needed',
    why: 'Leaf appears healthy with no visible disease symptoms.',
    organicAlternative: 'Neem preventive spray',
    dosage: '3 ml/L',
    harvestInterval: '0 days',
    frequency: 'Preventive every 15 days',
    severityNote: 'No treatment required. Maintain monitoring.',
    spray: false,
  },
  'Early Blight': {
    pesticide: 'Mancozeb or Chlorothalonil',
    why: 'Typical early blight lesions respond well to broad-spectrum fungicides.',
    organicAlternative: 'Bacillus subtilis',
    dosage: '2 g/L or 2 ml/L',
    harvestInterval: '5 days',
    frequency: 'Repeat after 7 days',
    severityNote: 'Start early to prevent spread.',
    spray: true,
  },
  'Late Blight': {
    pesticide: 'Metalaxyl + Mancozeb',
    why: 'Late blight is aggressive and needs systemic + contact protection.',
    organicAlternative: 'Copper-based bio fungicide',
    dosage: '2 g/L or 2 ml/L',
    harvestInterval: '7 days',
    frequency: 'Repeat after 5 days in severe cases',
    severityNote: 'High risk. Act quickly during humid weather.',
    spray: true,
  },
  'Leaf Mold': {
    pesticide: 'Chlorothalonil',
    why: 'Leaf mold responds well to protective fungicides.',
    organicAlternative: 'Bacillus subtilis',
    dosage: '2 ml/L',
    harvestInterval: '5 days',
    frequency: 'Repeat after 7 days',
    severityNote: 'Improve airflow and reduce humidity.',
    spray: true,
  },
  'Target Spot': {
    pesticide: 'Azoxystrobin',
    why: 'Target spot requires systemic fungicide coverage.',
    organicAlternative: 'Bacillus subtilis',
    dosage: '1 ml/L',
    harvestInterval: '5 days',
    frequency: 'Repeat after 7 days',
    severityNote: 'Focus on lower leaves and canopy gaps.',
    spray: true,
  },
  'Spider Mites': {
    pesticide: 'Abamectin',
    why: 'Mites feed on leaf underside and need targeted acaricide.',
    organicAlternative: 'Neem oil',
    dosage: '0.5 ml/L',
    harvestInterval: '3 days',
    frequency: 'Repeat after 5 days',
    severityNote: 'Spray underside of leaves thoroughly.',
    spray: true,
  },
};
