export const firebasePaths = {
  sensorsCurrent: 'SmartKisanSathi/sensors/current',
  sensorsHistory: 'SmartKisanSathi/sensors/history',
  historySensors: 'SmartKisanSathi/history/sensors',
  historyIrrigation: 'SmartKisanSathi/history/irrigation',
  historyDisease: 'SmartKisanSathi/history/disease',
  historyAlerts: 'SmartKisanSathi/history/alerts',
  controls: 'SmartKisanSathi/controls',
  automationWater: 'SmartKisanSathi/automation/water',
  pesticide: 'SmartKisanSathi/pesticide',
  pesticideHistory: 'SmartKisanSathi/pesticide/history',
  deviceStatusMain: 'SmartKisanSathi/deviceStatus/mainEsp32',
  deviceStatusCam: 'SmartKisanSathi/deviceStatus/esp32cam',
  aiDisease: 'SmartKisanSathi/aiDisease',
  analyticsToday: 'SmartKisanSathi/analytics/today',
  weatherCurrent: 'SmartKisanSathi/weather/current',
  weatherForecast: 'SmartKisanSathi/weather/forecast',
  reportsDaily: 'SmartKisanSathi/reports/daily',
  reportsWeekly: 'SmartKisanSathi/reports/weekly',
  reportsMonthly: 'SmartKisanSathi/reports/monthly',
  userProfiles: 'SmartKisanSathi/userProfiles',
  logs: 'SmartKisanSathi/logs',
  logsActions: 'SmartKisanSathi/logs/actions',
  adminGlobalAnalytics: 'SmartKisanSathi/admin/globalAnalytics',
  adminAlerts: 'SmartKisanSathi/admin/alerts',
  adminFarmsIndex: 'SmartKisanSathi/admin/farmsIndex',
} as const;
